### ISSUE TITLE
Wrong permissions on new file/folder

### ISSUE THREAD

**Issue by paulodiovani** [titoBouzout/SideBarEnhancements#203]
New files are being created with `666` permission (umask `000`).

They should respect logged user umask.

New Folders are being created with `775`, but these permissions [seens to be fixed on code](https://github.com/titoBouzout/SideBarEnhancements/blob/st3/sidebar/SideBarItem.py#L163).

**Comment by titoBouzout** [comment]
Can you please confirm that **with** the latest SideBarEnhancements and also latest ST (3084), when you right click the sidebar and select "New File..."  and "New Folder..." the file is created with 644 and the folder is created with 755 ?

**Comment by gerardroche** [comment]
This is still an issue in ST3 3084 / Linux: https://github.com/SublimeTextIssues/Core/issues/239#issuecomment-96447551

**Comment by titoBouzout** [comment]
Thanks, I asked about this package, not about ST.

**Comment by gerardroche** [comment]
This is still an issue for Sidebar Enhancements too.

ST3 3084 / Linux / SidebarEnhancements#6e52bd5

```
drwxr-xr-x 2 user user 4.0K Apr 27 00:02 dir_created_with_gedit
drwxr-xr-x 2 user user 4.0K Apr 27 00:01 dir_created_with_mkdir
drwxrwxr-x 2 user user 4.0K Apr 27 00:23 dir_created_with_sidebar_enhancements
drwxrwxr-x 2 user user 4.0K Apr 27 00:04 dir_created_with_sublime
-rw-r--r-- 1 user user    0 Apr 27 00:02 file_created_with_gedit
-rw-rw-rw- 1 user user    0 Apr 27 00:23 file_created_with_sidebar_enhancements
-rw-rw-rw- 1 user user  461 Apr 27 00:19 file_created_with_sublime
-rw-r--r-- 1 user user    0 Apr 27 00:01 file_created_with_touch
-rw-r--r-- 1 user user    0 Apr 27 00:03 file_created_with_vim
```

Tested via instructions here: https://github.com/SublimeTextIssues/Core/issues/239#issuecomment-54120750

**Comment by titoBouzout** [comment]
okei I changed 

-               os.makedirs(os.path.dirname(_to), 0o775);
+               os.makedirs(os.path.dirname(_to), 0o755);

Please bear with me , update this package, try again and let me know if Folders are created properly, (I use windows)

**Comment by gerardroche** [comment]
Yes, now folders are created with 755.

```
drwxr-xr-x 2 user user 4.0K Apr 27 02:40 dir_with_mkdir
drwxr-xr-x 2 user user 4.0K Apr 27 02:40 dir_with_sidebar_enhancements
```

**Comment by titoBouzout** [comment]
okei thanks, I added after file creation, 

    os.chmod(self.path(), 0o644) 

can you please check if files created via the sidebar hold the correct permissions, thanks a lot!

**Comment by gerardroche** [comment]
:+1: files are created with 644. These are good workaround fixes.

The underlying issue is Sublime Text itself. My guess is that umask is being set to zero somewhere in the core and not being reset to the user system setting. See https://github.com/SublimeTextIssues/Core/issues/239#issuecomment-54120750

If umask being set to zero in the core is the issue then when it's fixed in the core SidebarEnhancements will probably only need to remove the `os.chmod(self.path(), 0o644)` line.

**Comment by titoBouzout** [comment]
okei, thanks @gerardroche, to avoid the future bug then, I can do this:

		oldmask = os.umask(0o000)
		if oldmask == 0:
			os.chmod(self.path(), 0o644)
		os.umask(oldmask)

that is for file creation, but what happens with folder creation? I need to do the same thing? This is what I have now

		os.makedirs(os.path.dirname(_to), 0o755);

I can do 

		oldmask = os.umask(0o000)
		if oldmask == 0:
				os.makedirs(os.path.dirname(_to), 0o755);
		os.umask(oldmask)

**Comment by gerardroche** [comment]
I was thinking the same thing. 

For file creation that will prevent the future bug once ST releases a fix, *except* in the case where the user system umask is already 0. But vitually no user will set the umask to 0. So yes this is a really good future proof-ish fix. Then when ST releases a fix this code can be cleaned up.

For folders, I think once ST releases a fix directories can be created with `os.makedirs(os.path.dirname(_to));` rather than `os.makedirs(os.path.dirname(_to), 0o755);`, though I'm not sure either make difference.

If you're going to add these fixes then I suggest refactoring file and folder creation into a utility class so that changes only need to be made in one place.

Other than that :+1:

**Comment by titoBouzout** [comment]
OKEI done, thank you so much :)
