### ISSUE TITLE
Search by file name

### ISSUE THREAD

**Issue by montogeek** [titoBouzout/SideBarEnhancements#237]
It would be great the possibility to search in the project by file name. It would be a useful option.
Thanks!

**Comment by titoBouzout** [comment]
What does the menuitem named "Find Files Named…"? :P

**Comment by montogeek** [comment]
It does not copy and paste the file name automatically and start the search.

**Comment by titoBouzout** [comment]
That's a good idea, but not what you asked at first :P What happens if he user selects a folder? All the files will display, I don't know if it a good idea for files, but maybe is better than a empty search. Would you like to try a pull request?
https://github.com/titoBouzout/SideBarEnhancements/blob/st3/SideBar.py#L358-L370

**Comment by montogeek** [comment]
I have yo learn Python and right now I don't have the time. Can you? Just add me in the credits hahaha

**Comment by montogeek** [comment]
I have yo learn Python and right now I don't have the time. Can you? Just
add me in the credits hahaha

**Comment by titoBouzout** [comment]
I tested this, in all the situations we need to search for another file not the one that we click... so we end deleting always..
