### ISSUE TITLE
Context menu takes ages to open on a networked drive

### ISSUE THREAD

**Issue by qaisjp** [titoBouzout/SideBarEnhancements#292]
If you use WinSSHFs to open up a "drive" to a remote location, right clicking items take ages.

Here is a gif showing the difference between one file and another (one is on my D drive, the other is on my networked drive):
![Difference between networked and local files](https://cloud.githubusercontent.com/assets/923242/12074674/a4cfb1c0-b158-11e5-8bc9-fee16f1533f0.gif)

**Comment by titoBouzout** [comment]
Well that is kinda expected because some information about the selection should be obtained, it used to be worse, but  I did improved it a lot previously, I know it can even be better, and just now added another layer of cache, bu with more layers it  gets complicated.  Can you please let me know if upgrading and restarting sublime text, improves the situation?

**Comment by qaisjp** [comment]
sure, give me a second.

**Comment by qaisjp** [comment]
Hehe! Thank you! It is much faster now!

For onlookers, this was "fixed" in 8cfbaf152d77462950bd588949f10a07047648c2
