### ISSUE TITLE
Highlight current selected file.

### ISSUE THREAD

**Issue by brunano21** [titoBouzout/SideBarEnhancements#303]
Hi,

I have added a couple of folders to my project, so I can see all my files into the side bar. However I believe it's really useful to highlight the current shown file into the sidebar too, instead of having it listed only into the _Open Files_ section. 

Is that possible in some way?

Thanks.

**Comment by titoBouzout** [comment]
Yes, I use theme "Soda Dark 3.sublime-theme", so I have that vanilla theme installed, but also I have the following file in /Packages/User/Soda Dark 3.sublime-theme which has a section for keep highliting of the current opened file. 

https://dl.dropboxusercontent.com/u/9303546/SublimeText/personal/Soda%20Dark%203.sublime-theme

I cannot remember exactly what portion of the file, is the responsible for that thing you asked, please ask in the forums because Im not familiar with theme issues, and Im not interested. I guess the example file Im giving could give you hints on how to get that portion working.

Also, I really dislike that when you change focus of a file you lose your selection, because you need to reselect all over again, this is very frustrating for applying repetitive commands to files and folder and some git operations. So I strongly disagree with that behaviour of "Highlight current selected file" without any option to disable it.
