### ISSUE TITLE
Hide from sidebar | exlude from index - problems

### ISSUE THREAD

**Issue by AuthorProxy** [titoBouzout/SideBarEnhancements#319]
Why HideFromSidebar and ExcludeFromIndex not working and duplicating!?
Latest non-dev version: build 3114
Almost clear installation (on old it was worked as i remember, but i am not sure).

Screenshot is here: https://yadi.sk/i/2OeQoB3SspstY

**Comment by titoBouzout** [comment]
This happens because the package allows almost all variations of paths. 
1. absolute path, "c:/project/folder"
2. relative to the project "folder/"
3. simple folder "folder"

imagine that if you right click a more deep folder, the 2 option will be "folder/other" and 3 will be "other"

you seeing this because on the first level of every project the "relative path to the folder" is always the same as "simple folder name".
