### ISSUE TITLE
Question: Save Views is greyed out

### ISSUE THREAD

**Issue by sundarv85** [titoBouzout/SideBarEnhancements#409]
I’m able to see "Close Views" when I right click a folder. But the "Save Views" is greyed out. How does the "Save Views" work

Please note that I have multiple folders and I’m trying to "Save" a view, work on another folder, then close it and restore the "Saved View". Is this possible

**Comment by titoBouzout** [comment]
> the "Save Views" is greyed out.
That means that no views in that window are open for the folder you clicked.

Im not sure about your second question

**Comment by sundarv85** [comment]
Hi @titoBouzout 

The below two points are working:

1. Close Views is present only when some files within that folder are open
2. Close Views will be greyed out when no files are open

Since "Close Views" is present/available, I thought "Save Views" should also be possible (to save this view and restore it later) 

My goal was:

1. Open some files
2. Save this view
3. Close this view
4. Open this saved view at a later point of time.

Please correct me, if my understanding is wrong.

**Comment by titoBouzout** [comment]
I understand now. Save and close is only to close from editor and to save to disk.

I believe what you want in the default project system of sublime text, which does what you describing and maybe more. I cant guide you because I don't use the sublime text project system. I prefer to not deal with project files, I just like to work with folders.

Maybe you can try:
- open some random files, then go to Main menu bar - projects - save project as
- close all tabs
- open some other random files, then go to Main menu bar - projects - save project as 

Now you can switch between projects and in theory the tabs should be restored. Good luck handling project files

---------------

I use this to manage folders, but it does not auto close or reopen any tab 
https://github.com/titoBouzout/SideBarFolders
