### ISSUE TITLE
Sidebar does not show new files or remove deleted files

### ISSUE THREAD

**Issue by john-aws** [titoBouzout/SideBarEnhancements#441]
Using Sublime Text stable, build 4126 with SideBarEnhancements v5.0.45 on Mac OS Big Sur.

Steps to repro:

* use Sublime, open a folder
* open sidebar
* hit cmd+n to create a new file
* add minimal content to the new file
* hit cmd+s to save the new file to the same folder shown in sidebar

In my case, the new file will not appear in the sidebar file list. The file is definitely in the folder and will appear if I use right-click | Refresh. I would expect the filename to appear in the sidebar list at the time the file is saved to disk.

Additionally, if I use sidebar | right-click | delete and delete an existing file from the file list, that file will be deleted but it will not be removed from the sidebar file list. Again Refresh does correct this, but it should not be necessary to explicitly trigger a refresh.

**Comment by titoBouzout** [comment]
This package doesn't provide a CTRL+N keymap. That's just ST.

I suggest reporting it in https://github.com/sublimehq/sublime_text/issues because this is most likely a bug/edge case with the file system notifications. That could affect other operations.

In any case, I believed that using this package, if you "right click" the folder and press "New File.." it should trigger automatically a "refresh" command after naming the file.

You may also use this keymap (I never use it btw,  I just got used to right click >  new file)

```json
	{
		"keys": ["ctrl+t"],
		"command": "side_bar_new_file2"
	}
```
