### ISSUE TITLE
UndoRedoDontMoveCursor

### ISSUE THREAD

**Issue by ImportTaste** [titoBouzout/SideBarEnhancements#449]
Forgive me for using this repo to ask you about this, but I'm not sure what the best way to get a hold of you is.

Could you please restore the UndoRedoDontMoveCursor repo? This is something that I need and I wanted to figure out how it worked so I could apply it to Sublime Text 4.

**Comment by titoBouzout** [comment]
I dont have it.  You could have used my email address, which is on my profile page.

If I remember correctly there were many issues with it because the ST API wont work properly after an undo/redo action, because the api will return values in the past, while you can workaround some, there are some imposible to fix.

**Comment by titoBouzout** [comment]
Ah I see, it was on the spam folder
